import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { FORM_FIELDS } from "@/features/hod-approvals/forms/fields";
import type { FreeDocument, FreeRequest, FreeStep } from "@/lib/data";

const ORANGE = rgb(238 / 255, 77 / 255, 45 / 255);
const SUCCESS = rgb(0.18, 0.58, 0.32);
const DARK = rgb(0.1, 0.1, 0.1);
const MUTED = rgb(0.42, 0.42, 0.42);
const WHITE = rgb(1, 1, 1);
const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 34;
const GAP = 14;
const COL_WIDTH = (PAGE_WIDTH - MARGIN * 2 - GAP) / 2;
const BOTTOM_LIMIT = 64;

interface PdfState {
  doc: PDFDocument;
  page: PDFPage;
  y: number;
  font: PDFFont;
  bold: PDFFont;
}

function wrapLines(font: PDFFont, text: string, size: number, maxWidth: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  const splitWord = (word: string): string[] => {
    if (font.widthOfTextAtSize(word, size) <= maxWidth) return [word];
    const parts: string[] = [];
    let current = "";
    for (const char of Array.from(word)) {
      const candidate = current + char;
      if (current && font.widthOfTextAtSize(candidate, size) > maxWidth) {
        parts.push(current);
        current = char;
      } else {
        current = candidate;
      }
    }
    if (current) parts.push(current);
    return parts;
  };
  for (const word of words) {
    for (const part of splitWord(word)) {
      const candidate = line ? `${line} ${part}` : part;
      if (line && font.widthOfTextAtSize(candidate, size) > maxWidth) {
        lines.push(line);
        line = part;
      } else {
        line = candidate;
      }
    }
  }
  if (line) lines.push(line);
  return lines;
}

function drawFooter(state: PdfState): void {
  state.page.drawRectangle({ x: 0, y: 0, width: PAGE_WIDTH, height: 4, color: ORANGE });
  state.page.drawText("Generated by SPX Network Development App", { x: MARGIN, y: 22, size: 7, font: state.font, color: MUTED });
}

function newPageIfNeeded(state: PdfState, required: number): void {
  if (state.y - required < BOTTOM_LIMIT) {
    drawFooter(state);
    state.page = state.doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    drawHeader(state);
  }
}

function drawHeader(state: PdfState): void {
  state.y = PAGE_HEIGHT - 68;
  state.page.drawRectangle({ x: 0, y: PAGE_HEIGHT - 20, width: PAGE_WIDTH, height: 20, color: ORANGE });
  state.page.drawText("SPX NETWORK DEVELOPMENT", { x: MARGIN, y: PAGE_HEIGHT - 35, size: 13, font: state.bold, color: ORANGE });
  state.page.drawText("HOD Approval", { x: MARGIN, y: PAGE_HEIGHT - 51, size: 8, font: state.font, color: MUTED });
  state.page.drawRectangle({ x: PAGE_WIDTH - 120, y: PAGE_HEIGHT - 42, width: 86, height: 20, color: SUCCESS });
  state.page.drawText("APPROVED", { x: PAGE_WIDTH - 110, y: PAGE_HEIGHT - 36, size: 11, font: state.bold, color: WHITE });
}

function drawSection(state: PdfState, title: string): void {
  newPageIfNeeded(state, 24);
  state.y -= 4;
  state.page.drawText(title.toUpperCase(), { x: MARGIN, y: state.y, size: 8, font: state.bold, color: ORANGE });
  state.y -= 9;
  state.page.drawLine({ start: { x: MARGIN, y: state.y }, end: { x: PAGE_WIDTH - MARGIN, y: state.y }, thickness: 0.6, color: ORANGE });
  state.y -= 7;
}

function drawWrapped(state: PdfState, text: string, x: number, maxWidth: number, size = 8, font = state.font): void {
  for (const line of wrapLines(font, text, size, maxWidth)) {
    newPageIfNeeded(state, 10);
    state.page.drawText(line, { x, y: state.y, size, font, color: DARK });
    state.y -= 9;
  }
}

function drawFieldRow(state: PdfState, label: string, value: string): void {
  const fullWidth = PAGE_WIDTH - MARGIN * 2;
  const lines = wrapLines(state.font, value || "Not provided", 8, fullWidth);
  const height = 8 + lines.length * 9 + 4;
  newPageIfNeeded(state, height);
  state.page.drawText(label.toUpperCase(), { x: MARGIN, y: state.y, size: 6, font: state.bold, color: MUTED });
  state.y -= 8;
  drawWrapped(state, value || "Not provided", MARGIN, fullWidth);
  state.y -= 4;
}

export async function buildHodApprovalPdf(request: FreeRequest, steps: FreeStep[], documents: FreeDocument[]): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const state: PdfState = { doc, page: doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]), y: 0, font, bold };
  drawHeader(state);

  drawSection(state, "Request");
  drawFieldRow(state, "Request Number", request.requestNumber || request.id);
  drawFieldRow(state, "Requester", `${request.requesterName} (${request.requesterEmail})`);
  drawFieldRow(state, "Status", request.status.replace(/_/g, " "));
  drawFieldRow(state, "Submitted", request.submittedAt ? new Date(request.submittedAt).toLocaleString() : "Not submitted");
  drawFieldRow(state, "Completed", request.completedAt ? new Date(request.completedAt).toLocaleString() : "-");

  for (const section of [...new Set(FORM_FIELDS.map((field) => field.section))]) {
    const fields = FORM_FIELDS.filter((field) => field.section === section && request.formData[field.key] !== undefined && String(request.formData[field.key]).trim() !== "");
    if (fields.length === 0) continue;
    drawSection(state, section);
    for (const field of fields) {
      drawFieldRow(state, field.label, String(request.formData[field.key]));
    }
  }

  drawSection(state, "Approval Steps");
  for (const step of steps) {
    drawFieldRow(state, `HOD ${step.sequence}`, `${step.approverName} (${step.approverEmail})`);
    drawFieldRow(state, `HOD ${step.sequence} Status`, `${step.status.replace(/_/g, " ")}${step.completedAt ? ` · ${new Date(step.completedAt).toLocaleString()}` : ""}`);
  }

  if (documents.length > 0) {
    drawSection(state, "Documents");
    for (const document of documents) {
      drawFieldRow(state, document.documentName, `${document.originalFilename} · v${document.versionNumber}`);
    }
  }

  drawFooter(state);
  return doc.save();
}
