import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { getRequestDetail } from "@/features/hod-approvals/repository";
import { FORM_FIELDS, formFromRow } from "@/features/hod-approvals/forms/fields";
import { formatDateTime } from "@/lib/time";
import { getUserById } from "@/lib/auth";

const ORANGE = rgb(238 / 255, 77 / 255, 45 / 255);
const SUCCESS = rgb(0.18, 0.58, 0.32);
const DARK = rgb(0.1, 0.1, 0.1);
const MUTED = rgb(0.42, 0.42, 0.42);
const LINE_COLOR = rgb(0.85, 0.85, 0.85);
const WHITE = rgb(1, 1, 1);
type PdfColor = ReturnType<typeof rgb>;
const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 34;
const GAP = 14;
const COL_WIDTH = (PAGE_WIDTH - MARGIN * 2 - GAP) / 2;
const BOTTOM_LIMIT = 64;

interface PdfState {
  doc: PDFDocument;
  page: PDFPage;
  y: number;
  font: PDFFont;
  bold: PDFFont;
}

function drawPageHeader(state: PdfState): void {
  state.y = PAGE_HEIGHT - 68;
  state.page.drawRectangle({
    x: 0,
    y: PAGE_HEIGHT - 20,
    width: PAGE_WIDTH,
    height: 20,
    color: ORANGE
  });
  state.page.drawText("GENERAL EXPANSIONS", {
    x: MARGIN,
    y: PAGE_HEIGHT - 35,
    size: 13,
    font: state.bold,
    color: ORANGE
  });
  state.page.drawText("HOD Approval", {
    x: MARGIN,
    y: PAGE_HEIGHT - 51,
    size: 8,
    font: state.font,
    color: MUTED
  });
  state.page.drawRectangle({
    x: PAGE_WIDTH - 120,
    y: PAGE_HEIGHT - 42,
    width: 86,
    height: 20,
    color: SUCCESS
  });
  state.page.drawText("APPROVED", {
    x: PAGE_WIDTH - 110,
    y: PAGE_HEIGHT - 36,
    size: 11,
    font: state.bold,
    color: WHITE
  });
}

function drawSection(state: PdfState, title: string): void {
  newPageIfNeeded(state, 24);
  state.y -= 4;
  state.page.drawText(title.toUpperCase(), {
    x: MARGIN,
    y: state.y,
    size: 8,
    font: state.bold,
    color: ORANGE
  });
  state.y -= 9;
  state.page.drawLine({
    start: { x: MARGIN, y: state.y },
    end: { x: PAGE_WIDTH - MARGIN, y: state.y },
    thickness: 0.6,
    color: ORANGE
  });
  state.y -= 7;
}

function wrapLines(font: PDFFont, text: string, size: number, maxWidth: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  const splitWord = (word: string): string[] => {
    if (font.widthOfTextAtSize(word, size) <= maxWidth) return [word];
    const parts: string[] = [];
    let current = "";
    for (const char of Array.from(word)) {
      const candidate = current + char;
      if (current && font.widthOfTextAtSize(candidate, size) > maxWidth) {
        parts.push(current);
        current = char;
      } else {
        current = candidate;
      }
    }
    if (current) parts.push(current);
    return parts;
  };
  for (const word of words) {
    for (const part of splitWord(word)) {
      const candidate = line ? `${line} ${part}` : part;
      if (line && font.widthOfTextAtSize(candidate, size) > maxWidth) {
        lines.push(line);
        line = part;
      } else {
        line = candidate;
      }
    }
  }
  if (line) lines.push(line);
  return lines;
}

function drawPageFooter(state: PdfState): void {
  state.page.drawRectangle({ x: 0, y: 0, width: PAGE_WIDTH, height: 4, color: ORANGE });
  state.page.drawText("Generated by SPX Expansions Workflows Portal", {
    x: MARGIN,
    y: 22,
    size: 7,
    font: state.font,
    color: MUTED
  });
}

function newPageIfNeeded(state: PdfState, requiredHeight: number): void {
  if (state.y - requiredHeight < BOTTOM_LIMIT) {
    drawPageFooter(state);
    state.page = state.doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    drawPageHeader(state);
  }
}

function drawWrappedText(
  state: PdfState,
  text: string,
  options: { size?: number; color?: PdfColor; font?: PDFFont; x?: number; maxWidth?: number; lineHeight?: number } = {}
): void {
  const size = options.size ?? 8;
  const font = options.font ?? state.font;
  const x = options.x ?? MARGIN;
  const maxWidth = options.maxWidth ?? PAGE_WIDTH - MARGIN * 2;
  const lines = wrapLines(font, text, size, maxWidth);
  for (const line of lines) {
    newPageIfNeeded(state, options.lineHeight ?? size + 2);
    state.page.drawText(line, { x, y: state.y, size, font, color: options.color ?? DARK });
    state.y -= options.lineHeight ?? size + 2;
  }
}

function drawField(state: PdfState, label: string, value: string, column: 0 | 1): void {
  const x = MARGIN + column * (COL_WIDTH + GAP);
  const maxWidth = COL_WIDTH;
  const lines = wrapLines(state.font, value || "Not provided", 8, maxWidth);
  newPageIfNeeded(state, 8 + lines.length * 9 + 4);
  state.page.drawText(label.toUpperCase(), {
    x,
    y: state.y,
    size: 6,
    font: state.bold,
    color: MUTED
  });
  state.y -= 8;
  drawWrappedText(state, value || "Not provided", { size: 8, x, maxWidth, lineHeight: 9, color: DARK });
}

function drawFieldRow(state: PdfState, left: [string, string], right: [string, string] | null): void {
  const leftLines = wrapLines(state.font, left[1] || "Not provided", 8, COL_WIDTH);
  const rightLines = right ? wrapLines(state.font, right[1] || "Not provided", 8, COL_WIDTH) : [];
  const needed = Math.max(8 + leftLines.length * 9, right ? 8 + rightLines.length * 9 : 0) + 4;
  newPageIfNeeded(state, needed);
  const rowY = state.y;
  state.y = rowY;
  drawField(state, left[0], left[1], 0);
  const afterLeft = state.y;
  state.y = rowY;
  if (right) {
    drawField(state, right[0], right[1], 1);
  }
  state.y = Math.min(state.y, afterLeft) - 4;
}

function budgetStatusLabel(status: string): string {
  if (status === "ABOVE_CPO_BUDGET") return "Above CPO Budget";
  if (status === "WITHIN_CPO_BUDGET") return "Within CPO Budget";
  return status || "Not selected";
}

export async function buildHodApprovalPdf(requestId: string): Promise<Uint8Array> {
  const detail = getRequestDetail(requestId);
  if (!detail) throw new Error("Request not found");
  const { request } = detail;
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const state: PdfState = { doc, page: doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]), y: 0, font, bold };
  drawPageHeader(state);

  const form = formFromRow(detail.data);

  drawSection(state, "Request");
  const rows: Array<[string, string]> = [];
  rows.push(["Request Number", request.requestNumber ?? request.id]);
  rows.push(["Requester", `${detail.requester?.name ?? "Unknown"} (${detail.requester?.email ?? ""})`]);
  rows.push(["Submitted", request.submittedAt ? formatDateTime(request.submittedAt) : "Not submitted"]);
  rows.push(["Completed", request.completedAt ? formatDateTime(request.completedAt) : "-"]);
  rows.push(["Status", "APPROVED"]);
  rows.push(["Confirmation", "This document confirms that the HOD Approval request has been approved."]);

  for (const field of FORM_FIELDS) {
    const raw = form[field.key];
    if (field.key === "cpoBudgetStatus") {
      rows.push([field.label, budgetStatusLabel(String(raw ?? ""))]);
    } else if (Array.isArray(raw)) {
      rows.push([field.label, raw.length > 0 ? raw.join(", ") : ""]);
    } else if (typeof raw === "string" && raw.trim() !== "") {
      rows.push([field.label, raw]);
    }
  }

  for (const step of detail.steps) {
    const approver = getUserById(step.approverId);
    const name = approver?.name ?? "Unknown";
    const email = approver?.email ?? "";
    const completedAt = step.completedAt ? formatDateTime(step.completedAt) : "-";
    rows.push([`HOD ${step.sequence}`, `${name} (${email})`]);
    rows.push([`HOD ${step.sequence} Completed`, completedAt]);
  }

  for (const userId of detail.watcherUserIds) {
    const watcher = getUserById(userId);
    if (watcher) rows.push(["Watcher", `${watcher.name} (${watcher.email})`]);
  }

  for (let i = 0; i < rows.length; i += 2) {
    const left = rows[i];
    const right = rows[i + 1] ?? null;
    if (i === 0) drawSection(state, "Request Details");
    drawFieldRow(state, left, right);
  }

  drawPageFooter(state);

  return doc.save();
}
